### ISSUE TITLE
lvim: Invalid configuration

### ISSUE THREAD

**Issue by Coien-rr** [mrbeardad/nvim#5]
![image](https://user-images.githubusercontent.com/83146518/211184761-701cce3a-78e2-4000-96c7-4bce1a473799.png)
![image](https://user-images.githubusercontent.com/83146518/211184779-2a891b13-f058-47c7-bf45-7c7659a477f1.png)

配置完后出现这个问题，貌似还是上一个commit同样的问题，可以修复一下嘛

**Comment by mrbeardad** [comment]
已修复
