### ISSUE TITLE
E492: 不是编辑器的命令: PackerSyncFailed to setup handlers for trouble.nvim

### ISSUE THREAD

**Issue by lizzy-0323** [mrbeardad/nvim#6]
在执行安装配置的脚本时报错
nvim 0.8
os:macos

**Comment by lizzy-0323** [comment]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/58327725/212232082-6f91fcd6-84ad-4c16-9714-23a41c457a7f.png">

**Comment by jackyliu16** [comment]
我在进行尝试的时候也出现了这个问题，使用的系统为优麒麟ubuntu Linux Dell 5.15.0-57-generic
在根据README要求安装所有插件的那一步与楼主出现了同样的问题，不过得到了更多的信息
![图片](https://user-images.githubusercontent.com/50787361/212527239-0603acdd-fe73-4635-9dfa-615cb187aa2a.png)
本来出于我对于这个软件的简单认知，想尝试通过`PackerInstall`还是啥的指令手动装载插件的，但是在命令模式没有出现可选的这个选项，也无法运行`:checkHealth`检查状态是否正确

**Comment by jackyliu16** [comment]
刚刚尝试了下lunarvim的稳定版本，感觉是稍微略显抽象，可能是我不太会用的问题吧...他现在的状态差不多是所有插件都没有出于运行状态的样子，我看到你的配置文件里面提供了右侧的滑块功能，但是很显然这里没有
`15:55:23 [WARN ] lvim: "Invalid configuration: /home/jacky/.config/lvim/lua/user/alpha.lua:16: bad argument #1 to 'insert' (table expected, got nil)" file="init.lua", line=49%`


![图片](https://user-images.githubusercontent.com/50787361/212528125-a8f1d3d6-714d-4142-a928-ea1540296263.png)
至于那些奇怪的地方，比如说字符没有正常显示的问题，是我安装的老问题了，一直没能解决，我目前也没怎么研究过这个编译器的底层的问题...
开始的时候我怀疑是因为我的neovim没有正确装载的问题（虽然他可以正常用），ubuntu的apt不提供最新版本的资源，因此我是下载了源文件然后直接运行的，可能存在缺失文件的问题
**但是**后来我根据[Building-Neovim](https://github.com/neovim/neovim/wiki/Building-Neovim)的指示重装了一次之后发现还是出现这个问题，就直接开摆了**（这个字体的问题在我安装nerd fonts后解决了）**

**Comment by mrbeardad** [comment]
Sorry for the late reply. 多半又是上游LunarVim不兼容更新导致。

**Comment by mrbeardad** [comment]
安装稳定版的LunarVim，可以卸载后重新安装，见https://www.lunarvim.org/docs/installation
![image](https://user-images.githubusercontent.com/54128430/215953419-f122b679-6167-4538-8f03-9aabafbb7fba.png)
